# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Libs's Blog
subtitle:
description:
keywords:
author: Libs
language:
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://iicm.tk
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: material-x

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

# material-x custom
#shortcut_icon: "/img/favicon.ico"
favicon: "/img/favicon.ico"

# >> 主题配置 ---------------------------------------------------------------------
# 导航栏
nav_menu:
  - name: 主页
    slug: home
    icon: fa-home
    url: /
  - name: 归档
    slug: archives
    icon: fa-archive
    url: /archives
  - name: 贴吧签到云
    target: _blank
    slug: projects
    icon: fa-cloud
    url: http://sign.iicm.tk
  - name: windows&office
    target: _blank
    slug: projects
    icon: fa-windows
    url: http://noki.tk

# 右边的小窗口，不想显示哪一项的注释掉对应的即可
widgets:
  # 博主信息，显示个人头像、格言、社交信息等
  author:
    enable: true
    avatar: /img/avatar.jpg # 头像，如果config中已经设置avatar了，这里可以不用写
    title: Libs's Blog # 博客名、头衔等等，居中显示
    motto: It's unfair. # 格言座右铭等等
    social: true # 是否显示社交信息（内容同页脚的社交信息）
  # 显示文章分类
  categories: false
  # 显示文章标签
  tagcloud: true
  # 显示网易云歌单
  musicid: 972241273 # 歌单id
  # 显示目录（在文章中设置toc:false可以隐藏单篇文章的目录）
  toc: true
  # 显示友链
  #links:
  #- name: xaoxuu's blog
  #  url: https://blog.xaoxuu.com

# 页脚社交信息
social:
  - icon: fa-envelope
    url: mailto:woiyyng@gamil.com
  - icon: fa-github
    url: https://github.com/libsgh
  - icon: fa-instagram
    url:
  - icon: fa-google-plus
    url:
  - icon: fa-twitter
    url:
  - icon: fa-music
    url: https://music.163.com/#/user/home?id=298158928
  - icon: fa-rss
    url: atom
  - icon: fa-telegram
    url:
  - icon: fa-vimeo
    url:
  - icon: fa-gitlab
    url:
  - icon: fa-linkedin
    url:
  - icon: fa-snapchat
    url:
  - icon: fa-steam
    url:
  - icon: fa-spotify
    url:
  - icon: fa-tumblr
    url:
  - icon: fa-youtube
    url:
  - icon: fa-weibo
    url:
  - icon: fa-weixin
    url:
  - icon: fa-qq
    url: 


# 推荐文章
recommended_posts:
  autoDisplay: false # 自动在文章底部显示推荐文章，如果你使用Material-X主题，这里要设置为false。
  server: https://api.truelaurel.com # 后端推荐服务器地址
  timeoutInMillis: 10000 # 服务时长，超过此时长，则使用离线推荐模式
  excludePattern: []
  titleHtml: <h4>推荐文章</h4> #自定义标题
  internalLinks: 3 # 内部文章数量
  externalLinks: 2 # 外部文章数量
  fixedNumber: false


# Search 确保_config中只有一个search，否则会冲突。
search:
  enable: true
  service: hexo
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# Less
less:
  compress: true
  
# valine
valine:
  enable: true # 如果你想用Valine评论系统，请设置enable为true
  appId: sThPRBXbYEDI8LFHyfhlv6m6-gzGzoHsz # 必填
  appKey: BsK3PJ2Cqxtliw5rRdHYWaLC # 必填
  guest_info: nick,mail,link #valine comment header info
  placeholder: 快来评论吧~ # valine comment input placeholder(like: Please leave your footprints )
  avatar: mp # gravatar style https://valine.js.org/avatar
  pageSize: 10 # comment list page size
  verify: false # valine verify code (true/false)
  notify: true # valine mail notify (true/false)
  lang: zh-cn
# >> 主题配置 ---------------------------------------------------------------------
